"""Playlist

Revision ID: 7044964cba97
Revises: 92fc0e3f2fc0
Create Date: 2023-05-21 19:01:33.132725+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7044964cba97"
down_revision = "92fc0e3f2fc0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track", sa.String(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist")
    # ### end Alembic commands ###
